export const assets = [
  {
    symbol: "KQ",
    label: "KQ",
    balance: "9,999",
    jpy: "≈ ¥9,999",
    color: "#C62828",
    icon: "fa-coins",
  },
  {
    symbol: "BTC",
    label: "BTC",
    balance: "0.0500",
    jpy: "≈ ¥760,000",
    color: "#F7931A",
    icon: "fa-bitcoin",
  },
  {
    symbol: "ETH",
    label: "ETH",
    balance: "0.8000",
    jpy: "≈ ¥464,000",
    color: "#627EEA",
    icon: "fa-diamond",
  },
  {
    symbol: "USDT",
    label: "USDT",
    balance: "500",
    jpy: "≈ ¥77,500",
    color: "#26A17B",
    icon: "fa-dollar-sign",
  },
  {
    symbol: "XRP",
    label: "XRP",
    balance: "200",
    jpy: "≈ ¥17,000",
    color: "#23292F",
    icon: "fa-bolt",
  },
  {
    symbol: "USDC",
    label: "USDC",
    balance: "300",
    jpy: "≈ ¥46,500",
    color: "#2775CA",
    icon: "fa-circle-dollar-to-slot",
  },
  {
    symbol: "JPYR",
    label: "JPYR",
    balance: "15,000",
    jpy: "≈ ¥15,000",
    color: "#DC2626",
    icon: null,
  },
  {
    symbol: "JPYC",
    label: "JPYC",
    balance: "8,000",
    jpy: "≈ ¥8,000",
    color: "#3B82F6",
    icon: null,
  },
  {
    symbol: "IZAKAYA",
    label: "IZA",
    balance: "1,200",
    jpy: "≈ ¥6,000",
    color: "#8B5CF6",
    icon: null,
  },
];

export const assetComposition = [28, 22, 13, 7, 5, 9, 6, 6, 4];

export const brokers = [
  {
    code: "XM",
    name: "XM Trading",
    accent: "#111827",
    account: "·· 256558",
    label: "既存の口座A",
  },
  {
    code: "GT",
    name: "FX GT",
    accent: "#7E22CE",
    account: "·· 029384",
    label: "既存の口座B",
  },
  {
    code: "Ex",
    name: "Exness",
    accent: "#FACC15",
    account: "·· 201991",
    label: "既存の口座C",
    darkText: true,
  },
  { code: "IC", name: "IC Markets", accent: "#1D4ED8" },
  { code: "AX", name: "AXIORY", accent: "#0F172A" },
  { code: "HF", name: "HFM (HotForex)", accent: "#DC2626" },
  { code: "VT", name: "Vantage", accent: "#059669" },
  { code: "FP", name: "FxPro", accent: "#7C3AED" },
  { code: "PP", name: "Pepperstone", accent: "#111827" },
  { code: "FM", name: "FP Markets", accent: "#0EA5E9" },
  { code: "TF", name: "Titan FX", accent: "#334155" },
];

export const initialAnnouncements = [
  {
    title: "サービス開始のお知らせ",
    date: "2026/2/20",
    body: "KING and QUEENのサービスを正式にリリースしました。海外FXの取引でKQトークンが貯まる新しい体験をお楽しみください。",
    tags: [
      { label: "アップデート", tone: "success" },
      { label: "重要", tone: "danger" },
    ],
    priority: true,
    read: false,
  },
  {
    title: "メンテナンスのお知らせ",
    date: "2026/2/22",
    body: "2月25日 0:00〜6:00 にシステムメンテナンスを実施します。メンテナンス中はサービスをご利用いただけません。",
    tags: [{ label: "メンテナンス", tone: "warn" }],
    read: false,
  },
  {
    title: "KQトークン付与率UPキャンペーン",
    date: "2026/2/23",
    body: "3月1日〜3月31日の期間中、全ブローカーのKQトークン付与率が1.5倍になります。",
    tags: [{ label: "キャンペーン", tone: "info" }],
    read: false,
  },
  {
    title: "ランクシステムについて",
    date: "2026/2/24",
    body: "Member / Silver / Gold の3段階ランクを導入しました。取引量に応じて倍率や手数料優遇が変わります。",
    tags: [{ label: "アップデート", tone: "success" }],
    read: false,
  },
  {
    title: "セキュリティアップデート",
    date: "2026/2/25",
    body: "二段階認証の強化を行いました。より安全にサービスをご利用いただけます。",
    tags: [{ label: "その他", tone: "neutral" }],
    read: false,
  },
];

export const rankConfig = {
  bronze: {
    name: "Member",
    short: "Member",
    icon: "fa-shield-alt",
    color: "#92400E",
    bg: "#FEF3C7",
    progress: 42,
    points: "4,200 pt",
    subtitle: "Next: Silver まであと 5,800 pt",
    benefitRate: "x1.00",
    benefitFee: "優遇なし",
    nextLine: "次のランク（Silver）",
    nextValue: "$50,000",
    currentValue: "$0",
  },
  silver: {
    name: "Silver",
    short: "Silver",
    icon: "fa-gem",
    color: "#9CA3AF",
    bg: "#F3F4F6",
    progress: 32,
    points: "16,800 pt",
    subtitle: "Next: Gold まであと 33,200 pt",
    benefitRate: "x1.20",
    benefitFee: "手数料 -25%",
    nextLine: "次のランク（Gold）",
    nextValue: "$200,000",
    currentValue: "$50,000",
  },
  gold: {
    name: "Gold",
    short: "Gold",
    icon: "fa-crown",
    color: "#D97706",
    bg: "#FFFBEB",
    progress: 100,
    points: "73,500 pt",
    subtitle: "MAX RANK",
    benefitRate: "x1.50",
    benefitFee: "手数料 -50%",
    nextLine: "次のランク",
    nextValue: "達成済み",
    currentValue: "$200,000",
  },
};

export const payoutAssetDefaults = {
  KQ: "9,999 KQ",
  BTC: "0.0500 BTC",
  ETH: "0.8000 ETH",
  USDT: "500 USDT",
  XRP: "200 XRP",
  USDC: "300 USDC",
  JPYR: "15,000 JPYR",
  JPYC: "8,000 JPYC",
  IZAKAYA: "1,200 IZAKAYA",
};

export const rewardItems = [
  {
    date: "2026/3/1",
    type: "付与",
    tone: "success",
    value: "+1,200 KQ / +0.005 BTC / +0.08 ETH",
    ref: "BATCH-2026-03",
  },
  {
    date: "2026/2/1",
    type: "付与",
    tone: "success",
    value: "+800 KQ / +100 USDT / +50 USDC",
    ref: "BATCH-2026-02",
  },
  {
    date: "2026/2/15",
    type: "出金",
    tone: "neutral",
    value: "-200 USDT",
    ref: "WITHDRAW-001",
  },
  {
    date: "2026/1/20",
    type: "調整",
    tone: "info",
    value: "+5,000 JPYR",
    ref: "ADJ-001",
  },
  {
    date: "2026/1/1",
    type: "付与",
    tone: "success",
    value: "+500 KQ / +300 IZAKAYA / +3,000 JPYC",
    ref: "BATCH-2026-01",
  },
];

export const menuSubPages = [
  "profile",
  "wallet",
  "payout",
  "rewardHistory",
  "menuRank",
  "accountSettings",
  "kyc",
  "history",
];
